from alembic import op
import sqlalchemy as sa
revision="0001_initial"; down_revision=None; branch_labels=None; depends_on=None
def upgrade():
    op.create_table("policies", sa.Column("id",sa.String(100),primary_key=True), sa.Column("name",sa.String(255),nullable=False), sa.Column("description",sa.Text()), sa.Column("active_version",sa.String(50),nullable=False), sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()), sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("policy_versions", sa.Column("id",sa.String(150),primary_key=True), sa.Column("policy_id",sa.String(100),sa.ForeignKey("policies.id"),nullable=False), sa.Column("version",sa.String(50),nullable=False), sa.Column("effective_from",sa.String(40)), sa.Column("effective_to",sa.String(40)), sa.Column("status",sa.String(30),nullable=False), sa.Column("rules",sa.JSON(),nullable=False), sa.Column("source_references",sa.JSON(),nullable=False), sa.Column("created_at",sa.DateTime(timezone=True),nullable=False), sa.UniqueConstraint("policy_id","version",name="uq_policy_version"))
    op.create_table("authorization_requests", sa.Column("id",sa.String(36),primary_key=True), sa.Column("external_request_id",sa.String(120),unique=True), sa.Column("idempotency_key",sa.String(180),unique=True), sa.Column("status",sa.String(50),nullable=False), sa.Column("decision",sa.String(50)), sa.Column("patient",sa.JSON(),nullable=False), sa.Column("provider",sa.JSON(),nullable=False), sa.Column("plan",sa.JSON(),nullable=False), sa.Column("service",sa.JSON(),nullable=False), sa.Column("clinical",sa.JSON(),nullable=False), sa.Column("documents",sa.JSON(),nullable=False), sa.Column("extraction_confidence",sa.Float()), sa.Column("missing_information",sa.JSON(),nullable=False), sa.Column("conflicting_information",sa.JSON(),nullable=False), sa.Column("created_at",sa.DateTime(timezone=True),nullable=False), sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_authorization_status","authorization_requests",["status"]); op.create_index("ix_authorization_decision","authorization_requests",["decision"])
    op.create_table("rule_evaluations", sa.Column("id",sa.String(36),primary_key=True), sa.Column("request_id",sa.String(36),sa.ForeignKey("authorization_requests.id",ondelete="CASCADE"),nullable=False), sa.Column("rule_id",sa.String(100),nullable=False), sa.Column("rule_name",sa.String(255),nullable=False), sa.Column("result",sa.String(30),nullable=False), sa.Column("expected",sa.Text()), sa.Column("actual",sa.Text()), sa.Column("reason",sa.Text(),nullable=False), sa.Column("evidence",sa.JSON(),nullable=False), sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("nurse_reviews", sa.Column("id",sa.String(36),primary_key=True), sa.Column("request_id",sa.String(36),sa.ForeignKey("authorization_requests.id",ondelete="CASCADE"),nullable=False), sa.Column("status",sa.String(30),nullable=False), sa.Column("assigned_to",sa.String(150)), sa.Column("reviewer_decision",sa.String(50)), sa.Column("notes",sa.Text()), sa.Column("created_at",sa.DateTime(timezone=True),nullable=False), sa.Column("completed_at",sa.DateTime(timezone=True)))
    op.create_index("ix_nurse_reviews_status","nurse_reviews",["status"])
    op.create_table("audit_events", sa.Column("id",sa.String(36),primary_key=True), sa.Column("request_id",sa.String(36),sa.ForeignKey("authorization_requests.id",ondelete="SET NULL")), sa.Column("event_type",sa.String(100),nullable=False), sa.Column("actor",sa.String(150),nullable=False), sa.Column("payload",sa.JSON(),nullable=False), sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_audit_request_id","audit_events",["request_id"])
def downgrade():
    op.drop_table("audit_events"); op.drop_table("nurse_reviews"); op.drop_table("rule_evaluations"); op.drop_table("authorization_requests"); op.drop_table("policy_versions"); op.drop_table("policies")
